class TripSignupWaiver
  TEXT = <<~TEXT.squish.freeze
    Liability Release: BY SIGNING THIS DOCUMENT I AGREE TO GIVE UP CERTAIN LEGAL RIGHTS THAT I MAY HAVE IN THE EVENT I BECOME INJURED WHILE ENGAGING IN ACTIVITIES
WITH THE CRAGMONT CLIMBING CLUB. I WISH TO ENGAGE IN ROCK CLIMBING WITH CRAGMONT CLIMBING CLUB MEMBERS AND OTHERS WHO ENGAGE IN ROCK
CLIMBING AND MOUNTAINEERING ACTIVITIES SPONSORED BY THE CLUB. I UNDERSTAND THAT ROCK CLIMBING AND MOUNTAINEERING ARE INHERENTLY
DANGEROUS ACTIVITIES THAT INVOLVE RISK OF SERIOUS INJURY OR DEATH. I UNDERSTAND THAT, ALTHOUGH IT IS THE GOAL OF THE CRAGMONT CLIMBING CLUB
TO ALWAYS CLIMB IN A MANNER THAT IS SAFE, INJURY IS NEVERTHELESS POSSIBLE. IN ORDER TO PARTICIPATE IN THESE ACTIVITIES, I AGREE TO ASSUME THE RISK OF ANY INJURY THAT MAY OCCUR, AND I PROMISE THAT I WILL NOT HOLD THE CRAGMONT CLIMBING CLUB, ITS MEMBERS AND THOSE ASSOCIATED WITH IT
RESPONSIBLE IF I BECOME INJURED.


IN ADDITION, I RELEASE THE CRAGMONT CLIMBING CLUB, ITS MEMBERS AND THOSE ASSOCIATED WITH IT FROM ALL CLAIMS I MAY HAVE FOR INJURY OR LOSS
RESULTING FROM NEGLIGENCE OR OTHER ACTS OR OMISSIONS OF MEMBERS OR THOSE ASSOCIATED WITH THE CRAGMONT CLIMBING CLUB.
I UNDERSTAND THAT THE CRAGMONT CLIMBING CLUB IS NOT A TEACHING OR INSTRUCTIONAL ORGANIZATION AND THAT IT IS MY RESPONSIBILITY TO PROVIDE
FOR MY OWN INSTRUCTION IN CLIMBING TECHNIQUES AND SAFETY.

 

I PROMISE THAT I WILL CAREFULLY FOLLOW ALL INSTRUCTION PROVIDED BY MEMBERS OR THOSE ASSOCIATED WITH THE CRAGMONT CLIMBING CLUB, AND WILL DO EVERYTHING POSSIBLE TO AVOID INJURY TO MYSELF AND OTHERS. I FURTHER AGREE TO DEFEND AND PAY ALL COSTS AND EXPENSES THAT THE CRAGMONT CLIMBING CLUB, ITS MEMBERS AND THOSE ASSOCIATED WITH IT MAY INCUR AS A CONSEQUENCE OF ANY LEGAL ACTION ARISING OUT OF INJURY TO MYSELF OR INJURY TO SOMEONE ELSE AS A RESULT OF MY ACT OR OMISSION. I STATE THAT I AM CURRENTLY COVERED BY MEDICAL INSURANCE FOR ANY INJURIES THAT MAY OCCUR TO ME WHILE PARTICIPATING IN CRAGMONT CLIMBING CLUB ACTIVITIES. I PROMISE TO NEVER PARTICIPATE IN CRAGMONT CLIMBING CLUB ACTIVITIES IF I AM NOT COVERED BY THIS OR SIMILAR MEDICAL INSURANCE.


FINALLY, I INTEND FOR THIS DOCUMENT TO APPLY NOT ONLY TO MYSELF, BUT TO ANYONE ACTING ON MY BEHALF.
  TEXT

  def self.text
    TEXT
  end
end
